### ISSUE TITLE
smaccer player count

### ISSUE THREAD

**Issue by ItsSagi** [AIPTU/Smaccer#11]
![image](https://github.com/user-attachments/assets/7cd95607-c256-4c4a-8103-e492bf5431a0)

Add a plugin so that in the name tag we can put the people who are connected to a world

**Comment by ItsSagi** [comment]
how is going?

**Comment by AIPTU** [comment]
implements it! https://github.com/AIPTU/Smaccer/commit/411e135a54bf70d8ed8bd5b09e6d8fee736d187e
you can download it in poggit dev build or release tag
