### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Rmdmc** [AIPTU/Smaccer#16]
Thread: AsyncWorker#1
Error: Failed to fetch current commit ID
File: plugins/Smaccer.phar/src/aiptu/smaccer/tasks/LoadEmotesTask
Line: 33
Type: RuntimeException
Backtrace:
#0 pmsrc/src/scheduler/AsyncTask(81): aiptu\smaccer\tasks\LoadEmotesTask->onRun()
#1 (): pocketmine\scheduler\AsyncTask->run()

**Comment by AIPTU** [comment]
what's your OS?

**Comment by Rmdmc** [comment]
What is OS?

**Comment by AIPTU** [comment]
What are you running it on? Is it like hosting or vps like that?
