### ISSUE TITLE
suggestion- no gravity toggle

### ISSUE THREAD

**Issue by rest1npieces** [AIPTU/Smaccer#7]
i like using the human npc as decorations for builds, i think it'd be good to have a toggle for no gravity so we can have decorations in the air

**Comment by AIPTU** [comment]
Implemented! Check it out: https://github.com/AIPTU/Smaccer/commit/c2c16d2dabfabfbf5b0cdfaabd6f351ba6952fa7

You can download new version by release tag or poggit
