### ISSUE TITLE
How use plugin by source code?

### ISSUE THREAD

**Issue by MikhailGennadevic** [AIPTU/Smaccer#8]
`[09:34:54.042] [Server thread/CRITICAL]: Error: "Class "CortexPE\Commando\PacketHooker" not found" (EXCEPTION) in "plugins/Smaccer/src/aiptu/smaccer/Smaccer" at line 49
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(119): aiptu\smaccer\Smaccer->onEnable()
  #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)`
  
  I got this error

**Comment by AIPTU** [comment]
Is there a reason why you want to run from source?

**Comment by MikhailGennadevic** [comment]
I write plugin. I want see tips in VS code

**Comment by AIPTU** [comment]
well, you need install the dependency plugin

**Comment by AIPTU** [comment]
https://github.com/Paroxity/Commando
https://github.com/AIPTU/forms
if you don't need auto updater, you can set false in the config
https://github.com/ifera-mc/UpdateNotifier.git
